# Generated by Django 4.0.3 on 2022-05-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=122)),
                ('about_course', models.TextField(max_length=122)),
                ('title', models.TextField(max_length=122)),
                ('upload_file', models.FileField(upload_to='upload_file')),
                ('image', models.ImageField(upload_to='course/Y%/%m/%d')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='lesson_material/%Y/%m/%d/')),
                ('context1', models.TextField(max_length=122)),
                ('context2', models.TextField(max_length=122)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='cruiser.course')),
                ('lesson_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_theme', to='cruiser.course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
