# Generated by Django 4.0.3 on 2022-05-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruiser', '0002_alter_lesson_material_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about_course',
            field=models.TextField(max_length=122, verbose_name='О курсе'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=122, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course/Y%/%m/%d', verbose_name='Фотка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(max_length=122, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='lesson_material',
            name='context1',
            field=models.TextField(max_length=122, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='lesson_material',
            name='context2',
            field=models.TextField(max_length=122, verbose_name='Текст2'),
        ),
        migrations.AlterField(
            model_name='lesson_material',
            name='lesson',
            field=models.CharField(max_length=122, verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='lesson_material',
            name='lesson_theme',
            field=models.CharField(max_length=122, verbose_name='О уроке'),
        ),
        migrations.AlterField(
            model_name='lesson_material',
            name='title',
            field=models.CharField(max_length=122, verbose_name='Заголовок'),
        ),
    ]
