# Generated by Django 4.0.3 on 2022-05-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruiser', '0003_alter_course_about_course_alter_course_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_material',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_material', to='cruiser.course'),
        ),
    ]
